const firstP = document.querySelector(".first_p");
const secondP = document.querySelector(".second_p");
const thirdP = document.querySelector(".third_p");
const materialFirst = document.querySelector(".material_first");
const materialSecond = document.querySelector(".material_second");
const materialthird = document.querySelector(".material_third");
firstP.addEventListener("click", () => {
  materialFirst.style.display = "flex";
  materialSecond.style.display = "none";
  materialthird.style.display = "none";
  firstP.style.background = "#0e9e2f";
  firstP.style.color = "#fff";
  secondP.style.background = "#fff";
  secondP.style.color = "#686868";
  thirdP.style.background = "#fff";
  thirdP.style.color = "#686868";
});
secondP.addEventListener("click", () => {
  materialFirst.style.display = "none";
  materialthird.style.display = "none";
  materialSecond.style.display = "flex";
  secondP.style.background = "#0e9e2f";
  secondP.style.color = "#fff";
  firstP.style.background = "#fff";
  firstP.style.color = "#686868";
  thirdP.style.background = "#fff";
  thirdP.style.color = "#686868";
});
thirdP.addEventListener("click", () => {
  materialFirst.style.display = "none";
  materialthird.style.display = "flex";
  materialSecond.style.display = "none";
  thirdP.style.background = "#0e9e2f";
  thirdP.style.color = "#fff";
  secondP.style.background = "#fff";
  secondP.style.color = "#686868";
  firstP.style.background = "#fff";
  firstP.style.color = "#686868";
});
